---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
  - 'if COMMITTER_EMAIL !~ /gmail.com/ warn "Invalid email. Update with your github email" end'
bundler_args: --without system_tests
rvm:
  - 2.4.1
  - 2.1.9
env:
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec
matrix:
  fast_finish: true
  include:
    -
      env: CHECK=rubocop
    -
      env: CHECK="syntax lint"
    -
      env: CHECK=metadata_lint
branches:
  only:
    - master
    - /.*/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
